interval_minutes: 15

title_keywords:
  - "operator"
  - "pipeline"
  - "compressor"
  - "safety"
  - "industrial"
  - "sales"
  - "valve"
  - "regulator"
  - "gas"
  - "oil"

exclude:
  - "intern"
  - "senior director"

salary_floor: 80000

sources:
  greenhouse:
    companies:
      - "berkshirehathawayenergy"
      - "cheniere"
      - "exxonmobil"
      - "shell"
      - "chevron"
      - "enbridge"
      - "siemens"
      - "emerson"
      - "flowserve"

  lever:
    companies:
      - "airbnb"
      - "doordash"
      - "bakerhughes"
      - "honeywell"

  usajobs:
    enabled: true
    api_key: "YOUR_USAJOBS_API_KEY"
    query: "pipeline OR compressor OR valve OR regulator OR gas OR oil OR industrial safety"
    location: "Pennsylvania"

  ziprecruiter:
    enabled: true
    api_key: "YOUR_ZIPRECRUITER_API_KEY"
    query: "pipeline OR compressor OR valve OR regulator OR gas supply OR oil supply OR industrial sales OR energy safety"
    location: "Pennsylvania"
    radius_miles: 75
    days_age: 14
    per_page: 25

alerts:
  email:
    enabled: false
    smtp_host: "smtp.example.com"
    smtp_port: 587
    smtp_user: "you@example.com"
    smtp_pass: "app_password_here"
    to: "you@example.com"

  pushover:
    enabled: true
    user_key: "YOUR_USER_KEY"
    api_token: "YOUR_APP_TOKEN"
