interval_minutes: 15

title_keywords:
  - "operator"
  - "pipeline"
  - "compressor"
  - "safety"
  - "industrial"
  - "account manager"

exclude:
  - "intern"
  - "senior director"

salary_floor: 80000

sources:
  greenhouse:
    companies: ["columbia gas"]
  lever:
    companies: ["robinhood"]
  usajobs:
    enabled: true
    api_key: "YOUR_USAJOBS_API_KEY"
    query: "pipeline OR gas OR safety OR compliance"
    location: "Pennsylvania"
  ziprecruiter:
    enabled: true
    api_key: "YOUR_ZIPRECRUITER_API_KEY"
    query: "pipeline OR gas OR safety OR compliance OR industrial OR operator"
    location: "Pennsylvania"
    radius_miles: 75
    days_ago: 14
    per_page: 25

alerts:
  email:
    enabled: false
    smtp_host: "smtp.example.com"
    smtp_port: 587
    smtp_user: "you@example.com"
    smtp_pass: "app_password_here"
    to: "you@example.com"

  pushover:
    enabled: true
    user_key: "YOUR_USER_KEY"
    api_token: "YOUR_APP_TOKEN"
